In [1]:
##Playing around with the notebook
print('hello')
print('yes')

hello


In [2]:
def func(h):
  print(h)

yes


In [3]:
func('hello')

In [1]:
#importing tensorflow
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [3]:
#Creating tensors
#tf.Variable(value, datatype)
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

#Note: all of these are scalar values, so they will have a dimension of 0.

In [9]:
#Rank/Degree of Tensors: number of dimensions involved in the tensor
#Rank 0: scalar
string = tf.Variable("this is a string",tf.string)

#Arrays will have at least a rank of 1, 1 list = 1 dimension (a vector)
rank1_tensor = tf.Variable(['test','OK','Tim'],tf.string)

#List inside of a list --> rank of 2-->MATRIX
rank2_tensor = tf.Variable([['test','ok'],['test','yes']],tf.string)

#To determine the rank of a tensor, use tf.rank
tf.rank(number)
tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
#Shapes of tensors: looking at the dimensions
rank3_tensor = tf.Variable([['test','ok',"okay"],['test','yes',"okay"]],tf.string)
rank3_tensor.shape

#Note: If you added another list within the list, the rank would be 3

TensorShape([2, 3])

In [18]:
#Changing shape
rank3_tensor = tf.Variable([['test','ok',"okay"],['test','yes',"okay"],['okay','okay','okay']],tf.string)
rank3_tensor.shape

#So far, 3 elements in rank 2 tensor, 9 elements in rank 1 tensor. 

tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
print(tensor1) #1 list, 2 sets of sublists, 3 elements inside each sublist.
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [19]:
print(tensor1)
print(tensor2) #2 lists, 3 lists inside, 1 element inside
print(tensor3) #defined an initial shape of 3--> 3 lists, 6 elements, need to have 2 sublists
# Notice the changes in shape

#Valid shapes: multiply the value of each dimension. 3*2*1 = 6, 3*2 = 6, etc

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
#Types of Tensors
#Constant, Placeholder, and SparseTensor types cannot change during execution. Only Variable can.

In [ ]:
#Evaluating Tensors
#To evaluate a tensor, use this block of code:

with tf.Session() as sess:
  tensor.eval()

In [24]:
##RESHAPING EXAMPLES
t = tf.zeros([5,5,5,5]) #5*5*5*5 = 625 elements in the tensor

#Flattening this tensor
t = tf.reshape(t,[625])

#Say we have one dimension value, but we don't know the other: -1 tells tensorflow to infer what the shape needs to be
t = tf.reshape(t,[125,-1])
print(t)


tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]